steps:
  # Step 1: Checkout the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Misbahhassan08/testflask']
  
  # Step 2: Change directory to the repository
  - name: 'gcr.io/cloud-builders/docker'
  # your-repo-directory
    dir: 'testflask' 
    args: [
            'build',
            '-t',
            'gcr.io/myprojectems-435411/testflask:latest',
            '--cache-from',
            'gcr.io/myprojectems-435411/testflask:latest',
            '.'
          ]

  
  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'testflask'
    args: ['push', 'gcr.io/myprojectems-435411/testflask']

  
  
  # Step 4: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'testflask'
      - '--image'
      - 'gcr.io/myprojectems-435411/testflask'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--quiet'
    timeout: 3600s
 
# Store images in Google Artifact Registry 
images:
  - gcr.io/myprojectems-435411/testflask:latest
timeout: '3600s'  # Adjust timeout as necessary
options:
  logging: CLOUD_LOGGING_ONLY